In [ ]:
!pip install numpy

In [ ]:
import numpy as np

**Introduction to** **NumPy**

# Import Numpy

In [ ]:
#Declare Array
a = np.array([1,2,3]) #Vector
b = np.array([[1,2,3],[4,5,6]]) #Matrix
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]],[[9,10], [11,12]]]) #Tensor 3 Matrix, 6 Vector
print("Vector:")
print(a)
print("\n") #Print newline atau enter
print("Matrix:")
print(b)
print("\n") #Print newline atau enter
print("Tensor:")
print(c)

Vector:
[1 2 3]


Matrix:
[[1 2 3]
 [4 5 6]]


Tensor:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#Menentukan bentuk dari sebuah vector/matrix/tensor
vec_shape = np.shape(a)
mat_shape = np.shape(b)
tensor_shape = np.shape(c)
print(vec_shape)
print(mat_shape)
print(tensor_shape)

(3,)
(2, 3)
(3, 2, 2)


In [ ]:
#Cara lain untuk melihat shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 2, 2)


In [ ]:
#Mau mengambil elemen yang spesifik (r,c)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(b)
print(b[1,1]) #Mengambil elemen nomor 5 (1,1)indeksnya

[[1 2 3]
 [4 5 6]]
5


In [ ]:
#Mengambil kolom saja
print(b[:,1])

[2 5]


In [ ]:
#Mau menganti value dalam 2-D Array / Matrix
b[1,1] = 12
print(b)

[[ 1  2  3]
 [ 4 12  6]]


#Numpy Array types

##1.Numpy Array

In [ ]:
a_2 = np.array([4,5,6]) #Vector
b_2 = np.array([[11,12,13],[14,15,16]]) #Matrix

In [ ]:
print(a_2)
print(b_2)

[4 5 6]
[[11 12 13]
 [14 15 16]]


##2.Numpy Arange

In [ ]:
#Function untuk mendefinisikan nilai-nilai yang berjarak sama dalam interval yang ditentukan dalam array tsb
ar = np.arange(8)
print(ar)
ar2 = np.arange(1,8) #Start dan stop
print(ar2)
ar3 = np.arange(1,12,3) #Start, stop dan step
print(ar3)

[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[ 1  4  7 10]


##3.Numpy zeros

In [ ]:
#Function untuk menampilkan array baru dengan ukuran tertentu dan berisi 0
#defaultnya dtype adalah float
zeroes = np.zeros(5)
print(zeroes)
z2 = np.zeros((5,5), dtype = int)
print(z2)


[0. 0. 0. 0. 0.]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


##4.Numpy Ones

In [ ]:
#Function untuk menampilkan array baru dengan ukuran tertentu dan berisi 1
#defaultnya dtype adalah float
ones = np.ones(5)
print(ones)
one_2 = np.ones ((3,4), dtype = int)
print(one_2)

[1. 1. 1. 1. 1.]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#Manipulasi Array

##1.Reshape

In [ ]:
a = np.arange(1,13)
print(a)

#array diatas akan di re-shape menjadi matrix ordo 3x4
#Cara 1
b = np.reshape(a, (3,4))
print(b)

#Cara 2
b = a.reshape(3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##2.Flatten

In [ ]:
#Array kita kembalikan menjadi bentuk 1-D Array
#Cara 1
c = np.array(b).flatten()
print(c)

#Cara 2
c = b.flatten()
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


##3.Transpose

In [ ]:
#Cara 1
TransMat = np.array(b).transpose()
print(TransMat)


#Cara 2
TransMat = b.transpose()
print(TransMat)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**Axis / Axes**
digunakan untuk array yang lbh dari 1 dimensi

##4.Concatenate

In [ ]:


Arr1 = np.array([[1, 2, 3], [4, 5, 6]])
Arr2 = np.array([[21, 22, 23], [24, 25, 26], [27, 28, 29]])

# Menambahkan baris kosong ke Arr1 dengan tipe data integer
Arr1_padded = np.vstack((Arr1, np.zeros((1, Arr1.shape[1]), dtype=int)))  # Menambahkan satu baris kosong

# Concatenate dalam Axis 0
print("Concatenate 2 Matrix dalam Axis 0:")
print(np.concatenate((Arr1, Arr2)))

# Concatenate dalam Axis 1
print("\nConcatenate 2 Matrix dalam Axis 1:")
result = np.concatenate((Arr1_padded, Arr2), axis=1)
print(result)

Concatenate 2 Matrix dalam Axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [21 22 23]
 [24 25 26]
 [27 28 29]]

Concatenate 2 Matrix dalam Axis 1:
[[ 1  2  3 21 22 23]
 [ 4  5  6 24 25 26]
 [ 0  0  0 27 28 29]]


In [ ]:
Arr1 = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
Arr2 = np.array([[21, 22, 23], [24, 25, 26], [27, 28, 29]])


# Concatenate dalam Axis 0
print("Concatenate 2 Matrix dalam Axis 0:")
print(np.concatenate((Arr1, Arr2)))

# Concatenate dalam Axis 1
print("\nConcatenate 2 Matrix dalam Axis 1:")
print (np.concatenate((Arr1, Arr2), axis=1))

Concatenate 2 Matrix dalam Axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [21 22 23]
 [24 25 26]
 [27 28 29]]

Concatenate 2 Matrix dalam Axis 1:
[[ 1  2  3 21 22 23]
 [ 4  5  6 24 25 26]
 [ 7  8  9 27 28 29]]


##5.Stack

In [ ]:
Arr1 = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
Arr2 = np.array([[21, 22, 23], [24, 25, 26], [27, 28, 29]])

#Stack dalam Axis 0
print("Stack 2 Array dalam Axis 0:")
print(np.stack((Arr1, Arr1), axis=0))


#stack dalam Axis 1
print("Stack 2 Array dalam Axis 1:")
print(np.stack((Arr1, Arr2), axis=1))

Stack 2 Array dalam Axis 0:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Stack 2 Array dalam Axis 1:
[[[ 1  2  3]
  [21 22 23]]

 [[ 4  5  6]
  [24 25 26]]

 [[ 7  8  9]
  [27 28 29]]]


##6.Split

In [ ]:
import numpy as np
SplitArr = np.array([5,2,3,4,8,7,5,1,2])
#Split array menjadi 3 subarrays yang sama jumlahnya
SplitMat = np.split(SplitArr,3)
print(SplitMat)

#Split array di posisi index yang ditunjuk sesuai dengan 1-D array:
SplitMat2 = np.split(SplitArr,[1,3,5])
print(SplitMat2)

[array([5, 2, 3]), array([4, 8, 7]), array([5, 1, 2])]
[array([5]), array([2, 3]), array([4, 8]), array([7, 5, 1, 2])]


##7.Resize

In [ ]:
import numpy as np
#Mengubah size array, kalau size lebih besar makan terdapat salinan values
# Membuat array awal
ResizeArr = np.array([[1, 2, 3], [4, 5, 6]])

# Mengubah ukuran array menggunakan np.resize
ResizeMat = np.resize(ResizeArr, (3, 5))
print(ResizeMat)

[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]]


##8.Append

In [ ]:
InAppend = np.array([[1,2,3],[4,5,6]])

#Menggabungkan Array tanpa axis (1-D array)
Append1 = np.append (InAppend, [7,8,9])
print(Append1)

#Menggabungkan Array dalam axis 0
Append2 = np.append(InAppend, [[7,8,9]], axis = 0)
print("\n", Append2)

#Menggabungkan Array dalam axis 1
Append3 = np.append(InAppend, [[7,8,9], [10,11,12]], axis = 1)
print("\n", Append3)

[1 2 3 4 5 6 7 8 9]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


##9.Insert

In [ ]:
InArray = np.array([[1,2],[3,4],[5,6]])

#Insert tanpa axis, array akan di flatten (1-D Array)
Insert1 = np.insert(InArray, 2, [11,12])
print(Insert1)

#Insert Axis 0
Insert2 = np.insert(InArray, 2, [11,12], axis = 0)
print("\n", Insert2)

#Insert Axis 1
Insert3 = np.insert(InArray, 2, [11,12,13], axis = 1)
print("\n", Insert3)

[ 1  2 11 12  3  4  5  6]

 [[ 1  2]
 [ 3  4]
 [11 12]
 [ 5  6]]

 [[ 1  2 11]
 [ 3  4 12]
 [ 5  6 13]]


##10.Delete

In [ ]:
import numpy as np

# Membuat array dengan angka dari 1 hingga 8
InDel = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(InDel)

# Atau menggunakan np.arange untuk membuat array dari 1 hingga 8
InDel = np.arange(1, 9).reshape(2, 4)
print(InDel)

#Delete tanpa axis, flatten ke 1-D Array
print("\n")
Delete1 = np.delete(InDel, 2)
print(Delete1)

#Deleter dalam axis 0, Row ke-1 atau indeks 0 kehapus
Delete2 = np.delete(InDel,0, axis = 0)
print("\n", Delete2)

#Deleter dalam axis 1, Column kehapus
Delete3 = np.delete(InDel,1, axis = 1)
print("\n", Delete3)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


[1 2 4 5 6 7 8]

 [[5 6 7 8]]

 [[1 3 4]
 [5 7 8]]


##11.Unique

In [ ]:
InUnique = np.array([5,2,6,3,4,7,5,8,2,2,6,8])
print(InUnique)

#Value yang unik dari array:
Unique1 = np.unique(InUnique)  # Mengganti no dengan np
print("\n Value yang unik dari array:")
print(Unique1)

#Ada berapa value unik dalam array:
Unique2, indices = np.unique(InUnique, return_counts = True)
print("\n Ada berapa value unik dalam array:")
print(Unique2)
print(indices)

[5 2 6 3 4 7 5 8 2 2 6 8]

 Value yang unik dari array:
[2 3 4 5 6 7 8]

 Ada berapa value unik dalam array:
[2 3 4 5 6 7 8]
[3 1 1 2 2 1 2]


##12.Slice

In [ ]:
InSlice = np.arange(10)
print(InSlice)

#Slicing satu elemen
s2 = InSlice[2]
print("\n Slicing satu elemen:")
print(s2)

#Slicing mulai dari indeks sekian.....
s3 = InSlice[2:5]
print("\n Slicing mulai dari indeks sekian:")
print(s3)

#Slicing stop dari indeks sekian.....
s4 = InSlice[:5]
print("\n Slicing stop di indeks sekian:")
print(s4)

#Slicing stop dari indeks sekian.....
s5 = InSlice[2:5]
print("\n Slicing antara indeks-indeks sekian:")
print(s5)

[0 1 2 3 4 5 6 7 8 9]

 Slicing satu elemen:
2

 Slicing mulai dari indeks sekian:
[2 3 4]

 Slicing stop di indeks sekian:
[0 1 2 3 4]

 Slicing antara indeks-indeks sekian:
[2 3 4]


In [ ]:
print(InSlice)
#Slicing values dengan step/interval sekian....
s6 = InSlice[::2]
print("\n Slicing values dengan step/interval sekian:")
print(s6)

#Slicing dengan semua param
s6 = InSlice[::2]
print("\n Slicing values dengan step/interval sekian:")
print(s6)

[0 1 2 3 4 5 6 7 8 9]

 Slicing values dengan step/interval sekian:
[0 2 4 6 8]

 Slicing vdengan semua parameter:
[2 4 6]
